version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: always
    ports:
      - "3003:5000"
    volumes:
      - todo-data:/app/server/data
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=secure_jwt_secret_key_for_production
      - REACT_APP_API_URL=http://103.121.92.51:3003/api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  todo-data:
    driver: local 