version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: always
    ports:
      - "3003:5000"
    volumes:
      - todo-data:/app/server/data
    environment:
      - PORT=5000
      - NODE_ENV=production

volumes:
  todo-data:
    driver: local 